//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcp.Host.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AraclarDetay
    {
        public string AracID { get; set; }
        public Nullable<System.DateTime> AlinisTarihi { get; set; }
        public Nullable<System.DateTime> BakimTarihi { get; set; }
        public Nullable<System.DateTime> MuayeneTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Araclar Araclar { get; set; }
    }
}
