//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcp.Host.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelDetay
    {
        public int PersonelID { get; set; }
        public Nullable<int> UnvanID { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public Nullable<System.DateTime> IzinTarihi { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<int> EgitimID { get; set; }
        public Nullable<int> VardiyaID { get; set; }
        public Nullable<bool> CalismaDurumu { get; set; }
        public Nullable<int> AmirID { get; set; }
        public Nullable<bool> AmirMi { get; set; }
    
        public virtual Egitim Egitim { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Vardiya Vardiya { get; set; }
    }
}
