//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcp.Host.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vardiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vardiya()
        {
            this.PersonelDetay = new HashSet<PersonelDetay>();
        }
    
        public int VardiyaID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> BaslamaSaati { get; set; }
        public Nullable<System.DateTime> BitirmeSaati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelDetay> PersonelDetay { get; set; }
    }
}
