//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcp.Host.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vergi
    {
        public int VergiID { get; set; }
        public string VergiDairesi { get; set; }
        public Nullable<int> VergiNo { get; set; }
        public string VergiDairesiAdresi { get; set; }
        public Nullable<int> KurumID { get; set; }
    
        public virtual Kurumlar Kurumlar { get; set; }
    }
}
